services:
  payload:
    image: node:18-alpine
    ports:
      - '3001:3000'
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    working_dir: /home/node/app/
    command: sh -c "npm install -g pnpm && pnpm install && pnpm dev"
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    restart: always
    env_file: '.env'
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5431:5432'

volumes:
  # data:
  pgdata:
  node_modules:
